name: example
description: An example app for the grouped_buttons package.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0"

dependencies:
  flutter:
    sdk: flutter
  
  grouped_buttons: 
    path: ../

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
